# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula1taste',
            name='ordering',
        ),
    ]
