# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 22:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import premio.models


class Migration(migrations.Migration):

    dependencies = [
        ('premio', '0003_auto_20160914_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['ordering']},
        ),
        migrations.RemoveField(
            model_name='formula1taste',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='formula1taste',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='new',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='new',
            name='short_title',
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('enable', 'Habilitado'), ('disable', 'Deshabilitado')], default='enable', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=160, null=True, populate_from=premio.models.get_slug_notification, unique_with=('description', 'event_type__event_day__description', 'start_time')),
        ),
        migrations.AddField(
            model_name='formula1taste',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grandstand',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='drivers'),
        ),
        migrations.AlterField(
            model_name='grandstand',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(default=None, help_text='750 \xd7 523', upload_to='news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('Q', 'Q'), ('R', 'R')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premio.Driver'),
        ),
        migrations.AlterField(
            model_name='position',
            name='gap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='laps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premio.Phase'),
        ),
        migrations.AlterField(
            model_name='position',
            name='points',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='q1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='q2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='q3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='title',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='title',
            field=models.IntegerField(),
        ),
    ]
